### ISSUE TITLE
Error on train_mnist.py

### ISSUE THREAD

**Issue by suzukikbp** [chainer/chainermn#173]
I got this error below using chainermn v1.0.0. I dont get this error when I use v1.0.0.b1/2. 
Also no error based on trouble shooting [here](https://github.com/chainer/chainermn/blob/master/docs/source/installation/troubleshooting.rst), and i am using aws ec2 p2.8xlarge.

```
$ mpiexec -n 4 python3 examples/mnist/train_mnist.py
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 13, in <module>
    import chainermn
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/__init__.py", line 6, in <module>
    from chainermn import links  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/__init__.py", line 1, in <module>
    from chainermn.links.batch_normalization import MultiNodeBatchNormalization  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/batch_normalization.py", line 10, in <module>
    from chainermn.functions.batch_normalization import \
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/functions/batch_normalization.py", line 14, in <module>
    libcudnn = cudnn.cudnn
AttributeError: 'module' object has no attribute 'cudnn'
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 13, in <module>
    import chainermn
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/__init__.py", line 6, in <module>
    from chainermn import links  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/__init__.py", line 1, in <module>
    from chainermn.links.batch_normalization import MultiNodeBatchNormalization  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/batch_normalization.py", line 10, in <module>
    from chainermn.functions.batch_normalization import \
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/functions/batch_normalization.py", line 14, in <module>
    libcudnn = cudnn.cudnn
AttributeError: 'module' object has no attribute 'cudnn'
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 13, in <module>
    import chainermn
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/__init__.py", line 6, in <module>
    from chainermn import links  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/__init__.py", line 1, in <module>
    from chainermn.links.batch_normalization import MultiNodeBatchNormalization  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/batch_normalization.py", line 10, in <module>
    from chainermn.functions.batch_normalization import \
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/functions/batch_normalization.py", line 14, in <module>
    libcudnn = cudnn.cudnn
AttributeError: 'module' object has no attribute 'cudnn'
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 13, in <module>
    import chainermn
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/__init__.py", line 6, in <module>
    from chainermn import links  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/__init__.py", line 1, in <module>
    from chainermn.links.batch_normalization import MultiNodeBatchNormalization  # NOQA
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/links/batch_normalization.py", line 10, in <module>
    from chainermn.functions.batch_normalization import \
  File "/home/ubuntu/.local/lib/python3.4/site-packages/chainermn/functions/batch_normalization.py", line 14, in <module>
    libcudnn = cudnn.cudnn
AttributeError: 'module' object has no attribute 'cudnn'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19877,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by keisukefukuda** [comment]
(I edited your content so the error message is easier to read.)

I think this error is caused by Chainer, not ChainerMN. 
Chainer/Cupy was updated recently and cupy introduced an incompatibility. 
Which Chainer/Cupy version are you using?
Try Chainer 2.3.0 and corresponding CuPY version.

Thanks!

**Comment by suzukikbp** [comment]
Thank you for the quick reply. What is the cupy version corresponding to chainer 2.3.0?

**Comment by suzukikbp** [comment]
ah okay, cupy is included in chainer.  yeah I initially used 3.2.0 and now I reinstall 2.1 instead of 2.3.0 since there is no distribution chainer==2.3.0, and it worked. thank you!

**Comment by keisukefukuda** [comment]
Ah, `2.3.0` was my mistake. Thanks!
